### ISSUE TITLE
question: where to add api fetchdata calls

### ISSUE THREAD

**Issue by archenroot** [galstc05/flutter_master_detail#1]
Hell, I am very new to Flutter and Bloc, would you be so kind and navigate me where to put code that fetches the master data list from API and initially populates it?

I understand I can do it in for loop with the AddItemEvent method, but I was under the impression the right place is LoadItemsEvent. Or best, how to integrate it with FutureBuilder:
https://stackoverflow.com/questions/60345938/futurebuilder-and-snapshot-in-flutter-bloc-package

should I extend LoadItemEvent class by List<Item> attribute or what is the correct architecture placement?

Thank you.

**Comment by stefangaller** [comment]
I would put the logic that fetches the data inside a separate file that is then called within the BLoC.
That's exactly what the `_loadItems()` function is for.

This could look like this:

```
 Stream<MasterDetailState> _loadItems() async* {
    yield LoadingItemsState();
    try {
        final data = await myDataRepository.fetchData();
        yield LoadedItemsState(data);
    } catch (error, _){
        yield ErrorState(error);
    }
  }
```
